name: "CD Terraform"

on:
  push:
    branches: ["main", "feature/**"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Generate gcp-terraform-sa-key.json from secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY
      - name: Setup Google Cloud authentication
        run: echo "${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}" | base64 --decode > gcp-terraform-sa-key.json

      # Log in to Google Cloud using key file
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=gcp-terraform-sa-key.json

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Generate terraform.tfvars from secrets.TERRAFORM_TFVARS
      - name: Generate terraform.tfvars
        run: echo "${{ secrets.TERRAFORM_TFVARS }}" | base64 --decode > terraform.tfvars

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
